gui:
  authorColors:
    "leaf": cyan
    "fvrests": cyan
    "*": magenta
  mainPanelSplitMode: "vertical" # one of 'horizontal' | 'flexible' | 'vertical'
  showCommandLog: false
  showFileTree: false
  border: "rounded"
  theme:
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - reverse
git:
paging:
  # --dark prevents slow loading time: https://github.com/dandavison/delta/issues/1664
  pager: delta --dark --diff-highlight --minus-emph-style="reverse red" --minus-empty-line-marker-style="reverse red" --plus-emph-style="reverse green" --plus-empty-line-marker-style="reverse green" --hunk-header-style="line-number" --hunk-header-line-number-style="magenta" --file-style="yellow" --paging=never
  useConfig: true
